# Generated by Django 5.2.2 on 2025-06-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
