# Generated by Django 5.2.2 on 2025-06-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_details',
        ),
    ]
