# Generated by Django 5.2.2 on 2025-06-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_topic_subject_subject_topic_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_topic',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='topic_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='topic_number',
        ),
        migrations.AddField(
            model_name='subject',
            name='topics',
            field=models.JSONField(default=list),
        ),
    ]
