# Generated by Django 5.2.2 on 2025-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_unique_topic_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_name', 'chapter_number', 'chapter_name')},
        ),
        migrations.AddField(
            model_name='subject',
            name='topic_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='topic_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_name', 'chapter_number', 'chapter_name', 'topic_number', 'topic_name'), name='unique_topic_in_chapter'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='topics',
        ),
    ]
