# Generated by Django 5.2.2 on 2025-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_unique_together_subject_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_topic_in_chapter',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_name', 'chapter_number', 'chapter_name', 'topic_number', 'topic_name'), name='unique_topic_in_ch May 12, 2025 - 18:32:18 UTC+0530unique_topic_in_chapter'),
        ),
    ]
