# Generated by Django 5.2.2 on 2025-06-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_question_test_remove_test_subject_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='user',
        ),
    ]
