# Generated by Django 5.2.2 on 2025-06-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Jan-Feb', 'Jan-Feb'), ('Mar-Apr', 'Mar-Apr'), ('May-Jun', 'May-Jun'), ('Jul-Aug', 'Jul-Aug'), ('Sep-Oct', 'Sep-Oct'), ('Nov-Dec', 'Nov-Dec')], max_length=7, unique=True)),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
