# Generated by Django 5.2.2 on 2025-06-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='period',
            field=models.CharField(choices=[('Jan-Feb', 'Jan-Feb'), ('Mar-Apr', 'Mar-Apr'), ('May-Jun', 'May-Jun'), ('Jul-Aug', 'Jul-Aug'), ('Sep-Oct', 'Sep-Oct'), ('Nov-Dec', 'Nov-Dec')], max_length=7),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance_dashboard.studentdetail'),
            preserve_default=False,
        ),
    ]
