# Generated by Django 5.2.2 on 2025-06-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_dashboard', '0002_studentdetail_alter_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'period')},
        ),
    ]
